services:
  minecraft_server:
    container_name: ${NAME:-minecraft_server}
    build: .
    ports:
      - "${PORT:-25565}:25565"
    volumes:
      - ${DATADIR:-./minecraft_data}:/minecraft
    environment:
      - RAM=${RAM:-4G}
      - TYPE=${TYPE:-PaperMC}
      - PLUGINS=${PLUGINS:-False}
      - PORT=${PORT:-25565}
    env_file:
      - ${ENV_FILE:-.env}
    restart: unless-stopped
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: ${CPUS:-3}
          memory: ${MEMORY:-6G}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536