services:
  minecraft__server:
    container_name: ${NAME}
    build: .
    ports:
      - "${PORT}:25565"
    volumes:
      - ${DATADIR}:/minecraft
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 8G
